name: "leetcode-question-today"

on:
  schedule:
    - cron: "45 1 * * *" # 1 + 8 = 9 北京时间上午 9 点 45，因为观察到触发时间会有15分钟延迟，10点会准时通知
  workflow_dispatch:

jobs:
  today:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16

        - name: run cmd
          run: |
            go mod tidy
            go run main.go -wecom ${{ secrets.QUESTION_TODAY_TOKEN }}

        - name: echo
          run: |
            echo "notify ok" 
